version: "3"
services:
  web:
    env_file: .env
    profiles:
      - release
    container_name: cnu_web
    build: .
    command : python manage.py runserver 0:8000
    ports:
      - "${SERVER_HTTP_PORT}:8000"
    volumes:
      - .:/web
    depends_on:
      db:
        condition: service_healthy
        
  db:
    env_file: .env
    image: mysql
    container_name: cnu_db
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION',
    ]
    ports:
      - ${MYSQL_PORT}:3306
    expose:
      - 3306
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 1s
      retries: 30

  phpmyadmin:
    env_file: .env
    profiles:
      - dev
    image: phpmyadmin/phpmyadmin
    container_name: cnu_phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${PHPMYADMIN_PORT}:80
    links:
      - db:db